#!/bin/bash
# Use this script when the native dynamic linker is imcompatible
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  HERE=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
  SOURCE=$(readlink "$SOURCE")
  [[ "$SOURCE" != /* ]] && SOURCE="$HERE/$SOURCE"
done
HERE=$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)
export LD_LIBRARY_PATH="$HERE"
B=verifyta
exec -a $B "$HERE"/ld-linux-x86-64.so.2 "$HERE"/$B.bin "$@"
